forge "http://forge.puppetlabs.com"

mod 'puppetlabs-acl', '5.0.1'
mod 'puppetlabs-chocolatey', '8.0.0'
mod 'puppetlabs-stdlib', '9.6.0'
mod 'puppetlabs-powershell', '6.0.0'
mod 'puppetlabs-pwshlib', '1.2.2'
mod 'puppetlabs-registry', '5.0.1'
